"""add image fields to memories

Revision ID: 006c9e453b64
Revises: 
Create Date: 2026-08-25 19:12:50.770336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006c9e453b64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('memories', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'image_name')
    op.drop_column('memories', 'image_url')
    # ### end Alembic commands ###
